### ISSUE TITLE
🚧 Prepare questions for the "Meeting with Users" session on 18.10.2022

### ISSUE THREAD

**Issue by Aliroll** [WomenPlusPlus/deploy-impact-22-openedu-b#9]
Hello, so this session is coming up. Meeting Link: [meet.google.com/ord-iwxb-jix](http://meet.google.com/ord-iwxb-jix) 

I hope we will finally meet real Users (not sure who these will be) and ask them questions about How they use the platform or used to use it. 

I will be writing some, on the part of UX research. Guess we won't be able to conduct any big interviews or surveys, but still... Also, it would be nice to know ahead, of which particular User we will be talking to;

1. Who is the User we will be talking to?

Please write the questions you want to ask below:

1. ...

**Comment by MichalBurgunder** [comment]
Can you please post the time of the meeting? That way, everything needed for the meeting is included in the ticket.

Questions from my side: 
- What is the best feature of the platform in your opinion?
- What is your least favourite aspect of the platform so far?
- Apart from your least favourite aspect of the platform, what else would you like to see in the platform? Better related content, better UI, etc?
- How do you currently use the platform? Who uses it it, when, at what frequency do they stay on any given page, etc.?

**Comment by MichalBurgunder** [comment]
I see. Here the answer for clarity:

> Luisa
> Hi! Unfortunately the sessions will be deleted from the calendar as they are not confirmed and it just creates confusion.
> We will make the entry if it actually happens. Apologies for the misunderstand.

@Aliroll Can we close the ticket for now? We can reopen it at a later point (github won't delete it), if the session does in the end happen. This way, we can have a better overview of what we need to do.
